# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from edgeshard._grpc import edgeshard_pb2 as edgeshard__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in edgeshard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """===========================================================================
    Services
    ===========================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/edgeshard.WorkerService/RegisterWorker',
                request_serializer=edgeshard__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/edgeshard.WorkerService/Heartbeat',
                request_serializer=edgeshard__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.UnregisterWorker = channel.unary_unary(
                '/edgeshard.WorkerService/UnregisterWorker',
                request_serializer=edgeshard__pb2.UnregisterWorkerRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.UnregisterWorkerResponse.FromString,
                _registered_method=True)
        self.ListWorkers = channel.unary_unary(
                '/edgeshard.WorkerService/ListWorkers',
                request_serializer=edgeshard__pb2.ListWorkersRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.ListWorkersResponse.FromString,
                _registered_method=True)
        self.GetWorker = channel.unary_unary(
                '/edgeshard.WorkerService/GetWorker',
                request_serializer=edgeshard__pb2.GetWorkerRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.GetWorkerResponse.FromString,
                _registered_method=True)
        self.DeployService = channel.unary_unary(
                '/edgeshard.WorkerService/DeployService',
                request_serializer=edgeshard__pb2.DeployServiceRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.DeployServiceResponse.FromString,
                _registered_method=True)
        self.ListServices = channel.unary_unary(
                '/edgeshard.WorkerService/ListServices',
                request_serializer=edgeshard__pb2.ListServicesRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.ListServicesResponse.FromString,
                _registered_method=True)
        self.GetServiceStatus = channel.unary_unary(
                '/edgeshard.WorkerService/GetServiceStatus',
                request_serializer=edgeshard__pb2.GetServiceStatusRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.GetServiceStatusResponse.FromString,
                _registered_method=True)
        self.StopService = channel.unary_unary(
                '/edgeshard.WorkerService/StopService',
                request_serializer=edgeshard__pb2.StopServiceRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.StopServiceResponse.FromString,
                _registered_method=True)
        self.Profile = channel.unary_unary(
                '/edgeshard.WorkerService/Profile',
                request_serializer=edgeshard__pb2.ProfileRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.ApplyPlacement = channel.unary_unary(
                '/edgeshard.WorkerService/ApplyPlacement',
                request_serializer=edgeshard__pb2.ApplyPlacementRequest.SerializeToString,
                response_deserializer=edgeshard__pb2.ApplyPlacementResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """===========================================================================
    Services
    ===========================================================================

    """

    def RegisterWorker(self, request, context):
        """Worker registration and lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkers(self, request, context):
        """Cluster discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployService(self, request, context):
        """Service management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Profile(self, request, context):
        """Profiling
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyPlacement(self, request, context):
        """Placement (M7)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=edgeshard__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=edgeshard__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=edgeshard__pb2.HeartbeatRequest.FromString,
                    response_serializer=edgeshard__pb2.HeartbeatResponse.SerializeToString,
            ),
            'UnregisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterWorker,
                    request_deserializer=edgeshard__pb2.UnregisterWorkerRequest.FromString,
                    response_serializer=edgeshard__pb2.UnregisterWorkerResponse.SerializeToString,
            ),
            'ListWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkers,
                    request_deserializer=edgeshard__pb2.ListWorkersRequest.FromString,
                    response_serializer=edgeshard__pb2.ListWorkersResponse.SerializeToString,
            ),
            'GetWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorker,
                    request_deserializer=edgeshard__pb2.GetWorkerRequest.FromString,
                    response_serializer=edgeshard__pb2.GetWorkerResponse.SerializeToString,
            ),
            'DeployService': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployService,
                    request_deserializer=edgeshard__pb2.DeployServiceRequest.FromString,
                    response_serializer=edgeshard__pb2.DeployServiceResponse.SerializeToString,
            ),
            'ListServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServices,
                    request_deserializer=edgeshard__pb2.ListServicesRequest.FromString,
                    response_serializer=edgeshard__pb2.ListServicesResponse.SerializeToString,
            ),
            'GetServiceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceStatus,
                    request_deserializer=edgeshard__pb2.GetServiceStatusRequest.FromString,
                    response_serializer=edgeshard__pb2.GetServiceStatusResponse.SerializeToString,
            ),
            'StopService': grpc.unary_unary_rpc_method_handler(
                    servicer.StopService,
                    request_deserializer=edgeshard__pb2.StopServiceRequest.FromString,
                    response_serializer=edgeshard__pb2.StopServiceResponse.SerializeToString,
            ),
            'Profile': grpc.unary_unary_rpc_method_handler(
                    servicer.Profile,
                    request_deserializer=edgeshard__pb2.ProfileRequest.FromString,
                    response_serializer=edgeshard__pb2.ProfileResponse.SerializeToString,
            ),
            'ApplyPlacement': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyPlacement,
                    request_deserializer=edgeshard__pb2.ApplyPlacementRequest.FromString,
                    response_serializer=edgeshard__pb2.ApplyPlacementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edgeshard.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edgeshard.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """===========================================================================
    Services
    ===========================================================================

    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/RegisterWorker',
            edgeshard__pb2.RegisterWorkerRequest.SerializeToString,
            edgeshard__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/Heartbeat',
            edgeshard__pb2.HeartbeatRequest.SerializeToString,
            edgeshard__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/UnregisterWorker',
            edgeshard__pb2.UnregisterWorkerRequest.SerializeToString,
            edgeshard__pb2.UnregisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/ListWorkers',
            edgeshard__pb2.ListWorkersRequest.SerializeToString,
            edgeshard__pb2.ListWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/GetWorker',
            edgeshard__pb2.GetWorkerRequest.SerializeToString,
            edgeshard__pb2.GetWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/DeployService',
            edgeshard__pb2.DeployServiceRequest.SerializeToString,
            edgeshard__pb2.DeployServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/ListServices',
            edgeshard__pb2.ListServicesRequest.SerializeToString,
            edgeshard__pb2.ListServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/GetServiceStatus',
            edgeshard__pb2.GetServiceStatusRequest.SerializeToString,
            edgeshard__pb2.GetServiceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/StopService',
            edgeshard__pb2.StopServiceRequest.SerializeToString,
            edgeshard__pb2.StopServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Profile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/Profile',
            edgeshard__pb2.ProfileRequest.SerializeToString,
            edgeshard__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyPlacement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.WorkerService/ApplyPlacement',
            edgeshard__pb2.ApplyPlacementRequest.SerializeToString,
            edgeshard__pb2.ApplyPlacementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
