# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shard.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'shard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bshard.proto\x12\x0f\x65\x64geshard.shard\"O\n\rTensorMessage\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x12\n\nsession_id\x18\x04 \x01(\t\"u\n\x11SendTensorRequest\x12\x17\n\x0fsource_shard_id\x18\x01 \x01(\t\x12\x17\n\x0ftarget_shard_id\x18\x02 \x01(\t\x12.\n\x06tensor\x18\x03 \x01(\x0b\x32\x1e.edgeshard.shard.TensorMessage\"6\n\x12SendTensorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"@\n\x11RecvTensorRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0fsource_shard_id\x18\x02 \x01(\t\"f\n\x12RecvTensorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12.\n\x06tensor\x18\x03 \x01(\x0b\x32\x1e.edgeshard.shard.TensorMessage2\x8d\x02\n\x0cShardService\x12U\n\nSendTensor\x12\".edgeshard.shard.SendTensorRequest\x1a#.edgeshard.shard.SendTensorResponse\x12U\n\nRecvTensor\x12\".edgeshard.shard.RecvTensorRequest\x1a#.edgeshard.shard.RecvTensorResponse\x12O\n\x04Ping\x12\".edgeshard.shard.RecvTensorRequest\x1a#.edgeshard.shard.SendTensorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORMESSAGE']._serialized_start=32
  _globals['_TENSORMESSAGE']._serialized_end=111
  _globals['_SENDTENSORREQUEST']._serialized_start=113
  _globals['_SENDTENSORREQUEST']._serialized_end=230
  _globals['_SENDTENSORRESPONSE']._serialized_start=232
  _globals['_SENDTENSORRESPONSE']._serialized_end=286
  _globals['_RECVTENSORREQUEST']._serialized_start=288
  _globals['_RECVTENSORREQUEST']._serialized_end=352
  _globals['_RECVTENSORRESPONSE']._serialized_start=354
  _globals['_RECVTENSORRESPONSE']._serialized_end=456
  _globals['_SHARDSERVICE']._serialized_start=459
  _globals['_SHARDSERVICE']._serialized_end=728
# @@protoc_insertion_point(module_scope)
