# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import edgeshard._grpc.shard_pb2 as shard__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShardServiceStub:
    """Shard service — each shard runs this
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTensor = channel.unary_unary(
                '/edgeshard.shard.ShardService/SendTensor',
                request_serializer=shard__pb2.SendTensorRequest.SerializeToString,
                response_deserializer=shard__pb2.SendTensorResponse.FromString,
                _registered_method=True)
        self.RecvTensor = channel.unary_unary(
                '/edgeshard.shard.ShardService/RecvTensor',
                request_serializer=shard__pb2.RecvTensorRequest.SerializeToString,
                response_deserializer=shard__pb2.RecvTensorResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/edgeshard.shard.ShardService/Ping',
                request_serializer=shard__pb2.RecvTensorRequest.SerializeToString,
                response_deserializer=shard__pb2.SendTensorResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/edgeshard.shard.ShardService/CreateSession',
                request_serializer=shard__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=shard__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.RunPrefill = channel.unary_unary(
                '/edgeshard.shard.ShardService/RunPrefill',
                request_serializer=shard__pb2.InferenceRequest.SerializeToString,
                response_deserializer=shard__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.RunDecode = channel.unary_unary(
                '/edgeshard.shard.ShardService/RunDecode',
                request_serializer=shard__pb2.InferenceRequest.SerializeToString,
                response_deserializer=shard__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.ReleaseSession = channel.unary_unary(
                '/edgeshard.shard.ShardService/ReleaseSession',
                request_serializer=shard__pb2.ReleaseSessionRequest.SerializeToString,
                response_deserializer=shard__pb2.ReleaseSessionResponse.FromString,
                _registered_method=True)


class ShardServiceServicer:
    """Shard service — each shard runs this
    """

    def SendTensor(self, request, context):
        """Tensor transfer (inter-shard data plane)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecvTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Inference (remote client → shard)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPrefill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunDecode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTensor,
                    request_deserializer=shard__pb2.SendTensorRequest.FromString,
                    response_serializer=shard__pb2.SendTensorResponse.SerializeToString,
            ),
            'RecvTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.RecvTensor,
                    request_deserializer=shard__pb2.RecvTensorRequest.FromString,
                    response_serializer=shard__pb2.RecvTensorResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=shard__pb2.RecvTensorRequest.FromString,
                    response_serializer=shard__pb2.SendTensorResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=shard__pb2.CreateSessionRequest.FromString,
                    response_serializer=shard__pb2.CreateSessionResponse.SerializeToString,
            ),
            'RunPrefill': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPrefill,
                    request_deserializer=shard__pb2.InferenceRequest.FromString,
                    response_serializer=shard__pb2.InferenceResponse.SerializeToString,
            ),
            'RunDecode': grpc.unary_unary_rpc_method_handler(
                    servicer.RunDecode,
                    request_deserializer=shard__pb2.InferenceRequest.FromString,
                    response_serializer=shard__pb2.InferenceResponse.SerializeToString,
            ),
            'ReleaseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSession,
                    request_deserializer=shard__pb2.ReleaseSessionRequest.FromString,
                    response_serializer=shard__pb2.ReleaseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edgeshard.shard.ShardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edgeshard.shard.ShardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardService:
    """Shard service — each shard runs this
    """

    @staticmethod
    def SendTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.shard.ShardService/SendTensor',
            shard__pb2.SendTensorRequest.SerializeToString,
            shard__pb2.SendTensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecvTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.shard.ShardService/RecvTensor',
            shard__pb2.RecvTensorRequest.SerializeToString,
            shard__pb2.RecvTensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.shard.ShardService/Ping',
            shard__pb2.RecvTensorRequest.SerializeToString,
            shard__pb2.SendTensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.shard.ShardService/CreateSession',
            shard__pb2.CreateSessionRequest.SerializeToString,
            shard__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPrefill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.shard.ShardService/RunPrefill',
            shard__pb2.InferenceRequest.SerializeToString,
            shard__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunDecode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.shard.ShardService/RunDecode',
            shard__pb2.InferenceRequest.SerializeToString,
            shard__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.shard.ShardService/ReleaseSession',
            shard__pb2.ReleaseSessionRequest.SerializeToString,
            shard__pb2.ReleaseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
