master:
  ip: "192.168.1.119"
  port: "7856"
  interface: "enp4s0"
  lm_head_weight_path: "model_shards/shard_2.pth"

model_name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"

workers:
  - 
    name: worker0
    ip: "192.168.1.119"
    interface: "enp4s0"
    start: 0
    end: 16
    ckpt_path: "model_shards/shard_0.pth"

  - 
    name: worker1
    ip: "192.168.1.121"
    interface: "eno1"
    start: 16
    end: 32
    ckpt_path: "model_shards/shard_1.pth"