master:
  ip: "192.168.1.130"
  port: "7856"
  interface: "eth0"

worker:
  - worker0:
      ip: "192.168.1.129"
      interface: "eth0"

  - worker1:
      ip: "192.168.1.103"
      interface: "eth0"