master:
  ip: "192.168.1.130"
  port: "7856"
  interface: "eth0"
  lm_head_weight_path: ""

workers:
  - 
    name: worker0
    ip: "192.168.1.129"
    interface: "eth0"
    start: 0
    end: 16
    ckpt_path: ""

  - 
    name: worker1
    ip: "192.168.1.103"
    interface: "eth0"
    start: 16
    end: 32
    ckpt_path: ""