"""CLI commands: edgeshard service deploy/list/status/stop/init."""

from __future__ import annotations

from pathlib import Path

import yaml
from rich.console import Console
from rich.table import Table

console = Console()


# ---------------------------------------------------------------------------
# Well-known model registry (mirrors scheduler/model_info.py _KNOWN_MODELS)
# Used for generating smart defaults in service.yaml templates.
# ---------------------------------------------------------------------------
_KNOWN_MODELS: dict[str, dict] = {
    # Qwen2.5 family
    "Qwen/Qwen2.5-0.5B-Instruct": {
        "num_layers": 24, "hidden_size": 896, "estimated_memory_gb": 1.0,
    },
    "Qwen/Qwen2.5-1.5B-Instruct": {
        "num_layers": 28, "hidden_size": 1536, "estimated_memory_gb": 3.0,
    },
    "Qwen/Qwen2.5-3B-Instruct": {
        "num_layers": 36, "hidden_size": 2048, "estimated_memory_gb": 6.0,
    },
    "Qwen/Qwen2.5-7B-Instruct": {
        "num_layers": 28, "hidden_size": 3584, "estimated_memory_gb": 14.0,
    },
    "Qwen/Qwen2.5-14B-Instruct": {
        "num_layers": 48, "hidden_size": 5120, "estimated_memory_gb": 28.0,
    },
    "Qwen/Qwen2.5-72B-Instruct": {
        "num_layers": 80, "hidden_size": 8192, "estimated_memory_gb": 144.0,
    },
    # Llama2 family
    "meta-llama/Llama-2-7b-hf": {
        "num_layers": 32, "hidden_size": 4096, "estimated_memory_gb": 14.0,
    },
    "meta-llama/Llama-2-13b-hf": {
        "num_layers": 40, "hidden_size": 5120, "estimated_memory_gb": 26.0,
    },
    "meta-llama/Llama-2-70b-hf": {
        "num_layers": 80, "hidden_size": 8192, "estimated_memory_gb": 140.0,
    },
}


def init_service(
    model: str,
    output: str = "service.yaml",
    name: str | None = None,
    dtype: str = "float16",
    max_seq_len: int = 4096,
    policy: str = "default",
    force: bool = False,
) -> None:
    """Generate a service.yaml template from a model name.

    Auto-fills sensible defaults based on the model's known architecture.
    For unknown models, uses generic conservative defaults.

    Args:
        model: HuggingFace model ID or local path.
        output: Output YAML file path.
        name: Service name (auto-generated from model if omitted).
        dtype: Weight dtype (float16, bfloat16, float32).
        max_seq_len: Maximum sequence length.
        policy: Scheduling policy (default, latency-first, memory-balanced).
        force: Overwrite existing file if it exists.
    """
    out_path = Path(output)

    if out_path.exists() and not force:
        console.print(
            f"[red]Error: {out_path} already exists. Use --force to overwrite.[/red]"
        )
        raise SystemExit(1)

    # Derive service name from model path
    if name is None:
        model_slug = model.split("/")[-1].lower()  # e.g. "qwen2.5-7b-instruct"
        model_slug = model_slug.replace(" ", "-").replace("_", "-")
        name = model_slug

    # Look up model for smart defaults
    known_cfg = _resolve_known_model(model)

    # Build the service YAML
    service_data = {
        "name": name,
        "model": {
            "name": model,
            "revision": "main",
            "dtype": dtype,
        },
        "runtime": {
            "backend": "torch",
            "max_batch_size": 1,
            "max_sequence_length": max_seq_len,
        },
        "scheduling": {
            "policy": policy,
            "hints": {},
        },
        "deployment": {
            "backend": "docker",
            "shard_image": "edgeshard/shard:latest",
            "resource_limits": {},
        },
    }

    # Set resource limits based on model size
    if known_cfg is not None:
        mem_gb = known_cfg["estimated_memory_gb"]
        # Add 20% headroom for KV cache and activations
        resource_mem = int(mem_gb * 1.2)
        service_data["deployment"]["resource_limits"]["memory"] = f"{resource_mem}Gi"
        service_data["scheduling"]["hints"]["estimated_model_memory_gb"] = mem_gb
        service_data["scheduling"]["hints"]["num_layers"] = known_cfg["num_layers"]

    # Write YAML
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# EdgeShard service specification\n")
        f.write("# Generated by: edgeshard service init\n")
        f.write(f"# Model: {model}\n")
        if known_cfg is not None:
            f.write(f"# Layers: {known_cfg['num_layers']}, ")
            f.write(f"Hidden: {known_cfg['hidden_size']}\n")
        f.write("#\n")
        f.write("# Next steps:\n")
        f.write("#   1. Review and adjust settings below\n")
        f.write("#   2. edgeshard cluster snapshot -o cluster.yaml\n")
        f.write("#   3. edgeshard plan service.yaml --cluster-yaml cluster.yaml\n")
        f.write("#   4. edgeshard service deploy service.yaml\n")
        f.write("\n")
        yaml.safe_dump(service_data, f, default_flow_style=False, sort_keys=False)

    # Summary
    console.print(f"[bold green]Service specification generated![/bold green]")
    console.print()
    console.print(f"  Model:    [cyan]{model}[/cyan]")
    console.print(f"  Name:     [cyan]{name}[/cyan]")
    console.print(f"  Dtype:    [cyan]{dtype}[/cyan]")
    console.print(f"  Seq Len:  [cyan]{max_seq_len}[/cyan]")
    console.print(f"  Policy:   [cyan]{policy}[/cyan]")
    if known_cfg is not None:
        console.print(
            f"  Layers:   [green]{known_cfg['num_layers']}[/green] "
            f"(auto-detected)"
        )
        console.print(
            f"  Memory:   [green]~{known_cfg['estimated_memory_gb']} GB[/green] "
            f"(estimated)"
        )
    else:
        console.print(
            f"  [dim]Model not in registry — adjust resource_limits manually.[/dim]"
        )
    console.print()
    console.print(f"  Output:   [bold]{out_path}[/bold]")
    console.print()
    console.print("[dim]Next: edgeshard cluster snapshot -o cluster.yaml[/dim]")


def _resolve_known_model(model: str) -> dict | None:
    """Look up model in known registry with partial matching."""
    # Exact match
    if model in _KNOWN_MODELS:
        return _KNOWN_MODELS[model]

    # Partial match
    model_lower = model.lower()
    for known_name, cfg in _KNOWN_MODELS.items():
        if known_name.lower() in model_lower or model_lower in known_name.lower():
            return cfg

    return None


def deploy_service(service_yaml: str) -> None:
    """Deploy a service according to its specification.

    Args:
        service_yaml: Path to service specification YAML.
    """
    from edgeshard.common.config import ServiceSpec
    from edgeshard.common.logging import get_logger, setup_logging

    setup_logging(level="INFO", component="service")
    logger = get_logger("cli.service")

    path = Path(service_yaml)
    if not path.exists():
        console.print(f"[red]Error: Service YAML not found: {service_yaml}[/red]")
        raise SystemExit(1)

    spec = ServiceSpec.from_yaml(path)
    console.print(f"[bold green]Deploying service:[/bold green] {spec.name}")
    console.print(f"  Model: {spec.model.name}")

    # TODO (M8): Implement actual deployment logic.
    # This should:
    # 1. Validate spec
    # 2. Generate PlacementPlan (or use cached)
    # 3. Send deployment commands to Workers
    # 4. Wait for health checks
    # 5. Report service READY

    logger.info("Deployment not yet implemented")
    console.print("\n[dim]Deployment is not yet active. See milestone M8.[/dim]")


def list_services() -> None:
    """List all deployed services."""
    console.print("[bold]Deployed Services[/bold]")

    # TODO (M8): Connect to Master and fetch service list.
    table = Table(title="Services")
    table.add_column("Name", style="cyan")
    table.add_column("Model", style="magenta")
    table.add_column("Status", style="green")
    table.add_column("Shards", justify="right")

    console.print(table)
    console.print("\n[dim]Service listing is not yet active.[/dim]")


def show_service_status(name: str) -> None:
    """Show status of a deployed service.

    Args:
        name: Service name.
    """
    console.print(f"[bold]Service:[/bold] {name}")

    # TODO (M8): Connect to Master and fetch service status.
    console.print("[dim]Service status is not yet active.[/dim]")


def stop_service(name: str) -> None:
    """Stop a deployed service.

    Args:
        name: Service name.
    """
    console.print(f"[bold yellow]Stopping service:[/bold yellow] {name}")

    # TODO (M8): Send stop commands to Workers.
    console.print("[dim]Service stop is not yet active.[/dim]")
